export const NAVIGATED = "NAVIGATED";

export const CLASSES_REQUESTED = "CLASSES_REQUESTED";
export const CLASSES_REQUEST_SUCCEEDED = "CLASSES_REQUEST_SUCCEEDED";
export const CLASSES_REQUEST_FAILED = "CLASSES_REQUEST_FAILED";

export const DANCES_REQUESTED = "DANCES_REQUESTED";
export const DANCES_REQUEST_SUCCEEDED = "DANCES_REQUEST_SUCCEEDED";
export const DANCES_REQUEST_FAILED = "DANCES_REQUEST_FAILED";

export const EVENTS_REQUESTED = "EVENTS_REQUESTED";
export const EVENTS_REQUEST_SUCCEEDED = "EVENTS_REQUEST_SUCCEEDED";
export const EVENTS_REQUEST_FAILED = "EVENTS_REQUEST_FAILED";
